### PR TITLE
fix: HttpRequestDecoder NoClassDefFoundError

### LINKED ISSUE #547: [Bug] 使用spring-boot-starter-data-redis组件录制流量时报 java.lang.NoClassDefFoundError
### Search before asking

- [X] I have searched the existing [issues](https://github.com/arextest/arex-agent-java/issues) before asking.

### AREX Test Service

AREX Java Agent (arextest/arex-agent-java)

### Current Behavior

spring-boot-starter-data-redis 3.2.4  有问题： 流量录制redis流量的时候会报 java.lang.NoClassDefFoundError:
_HUBEJ1R(JP{(R)@6OZFYNG_tmb

实际上如果项目只用spring-boot-starter-data-redis 3.2.4的话 是不会引入netty的codec-http依赖
`U9N}}QV`}@4_0T4LE_@MG8

~K @)XE MBRZXEI4FH YY2V

而arex-agent修饰的netty模块内部是使用的netty-all包

### Expected Behavior

正常录制redis不报错且回放成功

### Steps To Reproduce

1. spring-boot-starter-data-redis 3.2.4
2. start recording will trigger

### Anything else

_No response_

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### PR DESCRIPTION
**Pull request by zlglbcmss**
fix #547

### CODE REVIEW

File: arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/NettyModuleInstrumentation.java [hunk 1]
```diff
@@ -16,7 +17,7 @@ public NettyModuleInstrumentation() {
          * because of the differences in MANIFEST.MF files between different versions of Netty
          * so we can't set bundle-Name for compatibility
          */
-        super("netty-v4");
+        super("netty-v4", hasClassNamed("io.netty.handler.codec.http.HttpRequestDecoder"));
```
Comment (lucas-myx) [inline arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/NettyModuleInstrumentation.java:20]: dont forget `netty-v3` module also need, thanks!

**Review by mr3 — APPROVED** [review]

**Review by lucas-myx — APPROVED** [review]
