### PR TITLE
fix: es java client record

### LINKED ISSUE #447: [Bug] http外部调用没有被录制到
### Search before asking

- [X] I have searched the existing [issues](https://github.com/arextest/arex-agent-java/issues) before asking.

### AREX Test Service

AREX Java Agent (arextest/arex-agent-java)

### Current Behavior

private final CloseableHttpClient newRiskHttpClient = HttpClients.createMinimal();
String result = newRiskHttpClient.execute(post, handler);
这个http调用没有录到数据

### Expected Behavior

newRiskHttpClient.execute(post, handler)和result结果被录制下来

### Steps To Reproduce

1. 版本org.apache.httpcomponents.httpclient:4.5.2
2. 在class中定义private final CloseableHttpClient newRiskHttpClient = HttpClients.createMinimal();
3. HttpPost post = new HttpPost(zeldaGateway + "/aaa");
            BasicResponseHandler handler = new BasicResponseHandler();
            ZeldaRequest request = genZztRiskRequest(token, user, feature, appid);
            if (ConstentParam.BAOHE_APPID.equalsIgnoreCase(appid)) {
                request.setEvent(ConstentParam.BAOHE_LOGIN);
            }
            buildRequest(post, request);
String result = newRiskHttpClient.execute(post, handler);
4.执行到newRiskHttpClient.execute，但没有被录制

### Anything else

_No response_

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### PR DESCRIPTION
**Pull request by mr3**
Fix #447

### CODE REVIEW

File: arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/BasicFutureInstrumentation.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+    protected ElementMatcher<TypeDescription> typeMatcher() {
+        return named("org.apache.http.concurrent.BasicFuture");
+    }
+
+    @Override
+    public List<MethodInstrumentation> methodAdvices() {
+        return Collections.singletonList(new MethodInstrumentation(isMethod()
+                .and(named("completed"))
+                .and(takesArguments(1)),
+            this.getClass().getName() + "$FutureAdvice"));
```
Comment (mokdeve) [inline arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/BasicFutureInstrumentation.java:38]: should be use `FutureAdvice.class.getName()`  instead of `this.getClass().getName() + "$FutureAdvice"`

File: arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientAdapter.java [hunk 2]
```diff
@@ -99,28 +94,21 @@ public HttpResponseWrapper wrap(HttpResponse response) {
             return buildEmptyBodyResponseWrapper(response.getStatusLine().toString(), locale, headers);
         }
 
-        byte[] responseBody;
+        // Compatible with org.apache.http.impl.client.InternalHttpClient.doExecute
+        bufferResponseEntity(response);
+
+        byte[] responseBody = new byte[0];
```
Comment (mokdeve) [inline arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientAdapter.java:100]: byte[] responseBody = new byte[0];

`ZERO_BYTE` instead of `new byte[0]` ?

File: arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/BasicFutureInstrumentation.java (hunk 1 above)
Comment (mr3) [reply arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/BasicFutureInstrumentation.java]: Fixed

File: arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientAdapter.java (hunk 2 above)
Comment (mr3) [reply arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientAdapter.java]: Fixed

**Review by lucas-myx — APPROVED** [review]

**Review by YongwuHe — APPROVED** [review]
